Default: &defaults
  database: mapix-web.sqlite3
  poolsize: 1

Development:
  <<: *defaults

Testing:
  database: mapix-web_test.sqlite3
  <<: *defaults

Staging:
  database: mapix-web_staging.sqlite3
  poolsize: 1
  <<: *defaults

Production:
  database: mapix-web_production.sqlite3
  poolsize: 1
  <<: *defaults
